export interface AsciiReportOptions {
  title?: string; // e.g. "DAILY SALES", "SHIFT DAY", "SHIFT NIGHT"
  outletName?: string;
  dateStr?: string;
  isConcluded?: boolean;
  totalSale?: number;
  wbcSale?: number;
  wStoreSale?: number;
  dayShiftSale?: number;
  nightShiftSale?: number;
  billedAmount?: number;
  nonBilledAmount?: number;
  upiAndCardAmount?: number;
  cashAmount?: number;
  loyalty?: number;
  includeShiftSection?: boolean;
}

const INNER_WIDTH = 32;

const fmtVal = (num?: number): string => {
  const val = num || 0;
  return '₹' + val.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
};

const formatRow = (
  borderLeft: string,
  label: string,
  valStr: string,
  borderRight: string,
  width = INNER_WIDTH
): string => {
  const neededSpaces = Math.max(1, width - label.length - valStr.length);
  return `${borderLeft}${label}${' '.repeat(neededSpaces)}${valStr}${borderRight}`;
};

export const generateAsciiReport = (opts: AsciiReportOptions): string => {
  const title = (opts.title || 'DAILY SALES').toUpperCase();
  const totalSale = opts.totalSale || 0;
  const wbcSale = opts.wbcSale || 0;
  const wStoreSale = opts.wStoreSale || 0;
  const dayShiftSale = opts.dayShiftSale || 0;
  const nightShiftSale = opts.nightShiftSale || 0;
  const billedAmount = opts.billedAmount || 0;
  const nonBilledAmount = opts.nonBilledAmount || 0;
  const upi = opts.upiAndCardAmount || 0;
  const cash = opts.cashAmount || 0;
  const loyalty = opts.loyalty || 0;


  const lines: string[] = [];

  // ── Box 1: SALES FORMATION (Double Line Box) ──
  lines.push('╔' + '═'.repeat(INNER_WIDTH) + '╗');
  const padLeft = Math.max(0, Math.floor((INNER_WIDTH - title.length) / 2));
  const padRight = Math.max(0, INNER_WIDTH - title.length - padLeft);
  lines.push('║' + ' '.repeat(padLeft) + title + ' '.repeat(padRight) + '║');
  lines.push('╠' + '═'.repeat(INNER_WIDTH) + '╣');
  lines.push(formatRow('║', '  TOTAL', fmtVal(totalSale) + ' ', '║'));
  lines.push(formatRow('║', '  ├─ WBC', fmtVal(wbcSale) + ' ', '║'));
  lines.push(formatRow('║', '  └─ W STORE', fmtVal(wStoreSale) + ' ', '║'));
  lines.push('╚' + '═'.repeat(INNER_WIDTH) + '╝');
  lines.push('');

  // ── Box 2: SHIFT (Single Line Box) ──
  const showShift = opts.includeShiftSection !== false;
  if (showShift) {
    const shiftHeader = '┌─ SHIFT ';
    const dashShift = Math.max(1, INNER_WIDTH + 1 - shiftHeader.length);
    lines.push(shiftHeader + '─'.repeat(dashShift) + '┐');
    lines.push(formatRow('│', ' ☀ DAY', fmtVal(dayShiftSale) + '  ', '│'));
    lines.push(formatRow('│', ' ◐ NIGHT', fmtVal(nightShiftSale) + '  ', '│'));
    lines.push('└' + '─'.repeat(INNER_WIDTH) + '┘');
    lines.push('');
  }

  // ── Box 3: BILLING (Single Line Box) ──
  const billingHeader = '┌─ BILLING ';
  const dashBilling = Math.max(1, INNER_WIDTH + 1 - billingHeader.length);
  lines.push(billingHeader + '─'.repeat(dashBilling) + '┐');
  lines.push(formatRow('│', ' BILLED', fmtVal(billedAmount) + '  ', '│'));
  lines.push(formatRow('│', ' NON-BILLED', fmtVal(nonBilledAmount) + '  ', '│'));
  lines.push('└' + '─'.repeat(INNER_WIDTH) + '┘');
  lines.push('');

  // ── Box 4: COLLECTION (Single Line Box) ──
  const collHeader = '┌─ COLLECTION ';
  const dashColl = Math.max(1, INNER_WIDTH + 1 - collHeader.length);
  lines.push(collHeader + '─'.repeat(dashColl) + '┐');
  lines.push(formatRow('│', ' UPI / CARD', fmtVal(upi) + '  ', '│'));
  lines.push(formatRow('│', ' CASH', fmtVal(cash) + '  ', '│'));
  lines.push(formatRow('│', ' LOYALTY', fmtVal(loyalty) + '  ', '│'));
  lines.push('└' + '─'.repeat(INNER_WIDTH) + '┘');
  lines.push('');

  // ── Footer ──
  const footerLabel = ' generated by invensync ';
  const totalWidth = INNER_WIDTH + 2;
  const footerPadLeft = Math.max(0, Math.floor((totalWidth - footerLabel.length) / 2));
  const footerPadRight = Math.max(0, totalWidth - footerLabel.length - footerPadLeft);
  lines.push('─'.repeat(footerPadLeft) + footerLabel + '─'.repeat(footerPadRight));

  return lines.join('\n');
};

export const generateWhatsAppAsciiMessage = (opts: AsciiReportOptions): string => {
  const site = opts.outletName || 'WildBean Cafe Rengali';
  const date = opts.dateStr ? ` - ${opts.dateStr}` : '';
  const asciiBox = generateAsciiReport(opts);

  return [
    `🏪 *${site}*${date ? `\n📅 *${opts.dateStr}*` : ''}`,
    '```',
    asciiBox,
    '```',
  ].join('\n');
};
