export const HSN_CHAPTERS = [
  { "code": "01", "name": "Live animals" },
  { "code": "02", "name": "Meat and edible meat offal" },
  { "code": "03", "name": "Fish and crustaceans" },
  { "code": "04", "name": "Dairy produce, eggs, honey" },
  { "code": "05", "name": "Products of animal origin (nes)" },

  { "code": "06", "name": "Live trees and plants" },
  { "code": "07", "name": "Edible vegetables" },
  { "code": "08", "name": "Edible fruits and nuts" },
  { "code": "09", "name": "Coffee, tea, spices" },
  { "code": "10", "name": "Cereals" },
  { "code": "11", "name": "Milling products" },
  { "code": "12", "name": "Oil seeds and fruits" },
  { "code": "13", "name": "Lac, gums, resins" },
  { "code": "14", "name": "Vegetable plaiting materials" },

  { "code": "15", "name": "Animal or vegetable fats and oils" },

  { "code": "16", "name": "Meat/fish preparations" },
  { "code": "17", "name": "Sugars and sugar confectionery" },
  { "code": "18", "name": "Cocoa and cocoa preparations" },
  { "code": "19", "name": "Cereal preparations" },
  { "code": "20", "name": "Vegetable/fruit preparations" },
  { "code": "21", "name": "Misc edible preparations" },
  { "code": "22", "name": "Beverages, alcohol, vinegar" },
  { "code": "23", "name": "Food industry residues, fodder" },
  { "code": "24", "name": "Tobacco and substitutes" },

  { "code": "25", "name": "Salt, sulphur, earths, stone" },
  { "code": "26", "name": "Ores, slag, ash" },
  { "code": "27", "name": "Mineral fuels, oils" },
  { "code": "28", "name": "Inorganic chemicals" },
  { "code": "29", "name": "Organic chemicals" },
  { "code": "30", "name": "Pharmaceutical products" },
  { "code": "31", "name": "Fertilizers" },
  { "code": "32", "name": "Tanning/dyeing extracts" },
  { "code": "33", "name": "Essential oils, perfumes" },
  { "code": "34", "name": "Soap, waxes" },
  { "code": "35", "name": "Albuminoidal substances" },
  { "code": "36", "name": "Explosives, pyrotechnics" },
  { "code": "37", "name": "Photographic goods" },
  { "code": "38", "name": "Misc chemical products" },

  { "code": "39", "name": "Plastics and articles" },
  { "code": "40", "name": "Rubber and articles" },
  { "code": "41", "name": "Raw hides and skins" },
  { "code": "42", "name": "Leather articles, bags" },
  { "code": "43", "name": "Furskins and artificial fur" },

  { "code": "44", "name": "Wood and articles of wood" },
  { "code": "45", "name": "Cork and articles" },
  { "code": "46", "name": "Straw, basketware" },
  { "code": "47", "name": "Pulp of wood" },
  { "code": "48", "name": "Paper and paperboard" },
  { "code": "49", "name": "Printed books, newspapers" },

  { "code": "50", "name": "Silk" },
  { "code": "51", "name": "Wool and animal hair" },
  { "code": "52", "name": "Cotton" },
  { "code": "53", "name": "Other vegetable textile fibres" },
  { "code": "54", "name": "Man-made filaments" },
  { "code": "55", "name": "Man-made staple fibres" },
  { "code": "56", "name": "Wadding, felt, nonwovens" },
  { "code": "57", "name": "Carpets and floor coverings" },
  { "code": "58", "name": "Special woven fabrics" },
  { "code": "59", "name": "Coated textile fabrics" },
  { "code": "60", "name": "Knitted or crocheted fabrics" },
  { "code": "61", "name": "Knitted apparel" },
  { "code": "62", "name": "Non-knitted apparel" },
  { "code": "63", "name": "Other textile articles" },

  { "code": "64", "name": "Footwear" },
  { "code": "65", "name": "Headgear" },
  { "code": "66", "name": "Umbrellas, walking sticks" },
  { "code": "67", "name": "Feathers, artificial flowers" },

  { "code": "68", "name": "Articles of stone, plaster" },
  { "code": "69", "name": "Ceramic products" },
  { "code": "70", "name": "Glass and glassware" },

  { "code": "71", "name": "Precious stones, jewellery" },

  { "code": "72", "name": "Iron and steel" },
  { "code": "73", "name": "Articles of iron and steel" },
  { "code": "74", "name": "Copper and articles" },
  { "code": "75", "name": "Nickel and articles" },
  { "code": "76", "name": "Aluminium and articles" },
  { "code": "77", "name": "Reserved" },
  { "code": "78", "name": "Lead and articles" },
  { "code": "79", "name": "Zinc and articles" },
  { "code": "80", "name": "Tin and articles" },
  { "code": "81", "name": "Other base metals" },
  { "code": "82", "name": "Tools, cutlery" },
  { "code": "83", "name": "Misc metal articles" },

  { "code": "84", "name": "Machinery and mechanical appliances" },
  { "code": "85", "name": "Electrical machinery and equipment" },

  { "code": "86", "name": "Railway locomotives" },
  { "code": "87", "name": "Vehicles" },
  { "code": "88", "name": "Aircraft, spacecraft" },
  { "code": "89", "name": "Ships and boats" },

  { "code": "90", "name": "Optical, medical instruments" },
  { "code": "91", "name": "Clocks and watches" },
  { "code": "92", "name": "Musical instruments" },

  { "code": "93", "name": "Arms and ammunition" },
  { "code": "94", "name": "Furniture, lighting" },
  { "code": "95", "name": "Toys, sports goods" },
  { "code": "96", "name": "Misc manufactured articles" },
  { "code": "97", "name": "Works of art, antiques" },

  { "code": "98", "name": "Special classification provisions" },
  { "code": "99", "name": "Reserved (services/SAC in GST)" }
]
